### ISSUE TITLE
Чат

### ISSUE THREAD

**Issue by RusanovKonstantin** [RusanovKonstantin/TeamFruit#6]
Создать чат, на основе использования Signal-R
Acceptance criteria:
1. Интеграция чата в основной проект
1. Создать чат, который позволяет двум пользователям общаться друг с другом
1. Историю сохранять не надо
1. Новый пользователь не видит истории сообщений

https://metanit.com/sharp/aspnet5/30.1.php
https://www.npmjs.com/package/@microsoft/signalr
https://www.npmjs.com/package/signalr

**Comment by jskonst** [comment]
https://metanit.com/sharp/aspnet5/30.1.php
