### ISSUE TITLE
Настройка сервера

### ISSUE THREAD

**Issue by RusanovKonstantin** [RusanovKonstantin/TeamFruit#7]
Настроить сервер на С#
1)Запросы к ISUKT
2)Знать ВСЕ ОСТАЛЬНОЕ

**Comment by jskonst** [comment]
Надо определять такие задачи, которые имеют четкие границы и критерии того, что они выполнены. Знать все остальное - звучит не очень

**Comment by K-Voland** [comment]
нужно
 <div id="form-ajax-node-content"><div style="overflow-x:auto;width:100%;"><table class="schedule" style="overflow: wrap" autosize="1"><tbody><tr><td rowspan="2" class="week">нед</td><td rowspan="2" class="time">Время</td><td colspan="7" class="zan">Занятия</td></tr><tr><td class="day">Понедельник</td><td class="day">Вторник</td><td class="day">Среда</td><td class="day">Четверг</td><td class="day">Пятница</td><td class="day" style="background-color:#fbdb69">Суббота</td><td class="day">Воскресенье</td></tr><tr><td rowspan="4" style="vertical-align: middle;font-weight: bold;">1</td><td class="time">08:00-09:35</td><td class="type-lk">Технологии программирования Константинов Е.С. лк. А206 <br>с 17.02.2020 по 11.05.2020</td><td>&nbsp;</td><td class="type-lab">Вычислительная математика Шергин В.В. лаб. А204 <br>с 19.02.2020 по 13.05.2020</td><td>&nbsp;</td><td class="type-pz">Экономика и управление производством Абрамова Е.А. пр.з. А205 <br>с 21.02.2020 по 15.05.2020</td><td class="type-lab">Технологии программирования Константинов Е.С. лаб. А306 <br>с 22.02.2020 по 16.05.2020</td><td>&nbsp;</td></tr><tr><td class="time">09:50-11:25</td><td class="type-pz">Психология и педагогика Клейман М.Б. пр.з. А102 <br>с 17.02.2020 по 11.05.2020</td><td>&nbsp;</td><td class="type-lab">Технологии программирования Константинов Е.С. лаб. А309 <br>с 19.02.2020 по 13.05.2020</td><td>&nbsp;</td><td class="type-lk">Философия Клейман М.Б. лк. К205 <br>с 21.02.2020 по 15.05.2020</td><td class="type-lk">Вычислительная математика Шергин В.В. лк. А317 <br>с 22.02.2020 по 16.05.2020</td><td>&nbsp;</td></tr><tr><td class="time">11:40-13:15</td><td class="type-lk">Электротехника и электроника Дунаев А.М. лк. Г306 <br>с 17.02.2020 по 11.05.2020</td><td class="type-pz">Элективные курсы по физической культуре и спорту - пр.з. спортзал <br>с 18.02.2020 по 12.05.2020</td><td>&nbsp;</td><td class="type-pz">Элективные курсы по физической культуре и спорту - пр.з. спортзал <br>с 20.02.2020 по 14.05.2020</td><td class="type-pz">Иностранный язык Врыганова К.А., Ганина В.В. пр.з. А305 <br>с 21.02.2020 по 15.05.2020</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td class="time">13:30-15:05</td><td>&nbsp;</td><td class="type-lk">Информационные технологии Бобков С.П. лк. А206 <br>с 18.02.2020 по 12.05.2020</td><td>&nbsp;</td><td class="type-pz">Философия Клейман М.Б. пр.з. К307 <br>с 20.02.2020 по 14.05.2020</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td rowspan="5" style="background-color:#fbdb69;vertical-align: middle;font-weight: bold;">2</td><td class="time">08:00-09:35</td><td>&nbsp;</td><td>&nbsp;</td><td class="type-lk">Вычислительная математика Шергин В.В. лк. А206 <br>с 12.02.2020 по 20.05.2020</td><td>&nbsp;</td><td class="type-pz">Экономика и управление производством Абрамова Е.А. пр.з. А205 <br>с 14.02.2020 по 22.05.2020</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td class="time">08:00-11:25</td><td class="type-lab">Электротехника и электроника - лаб. Д1.14 <br>с 10.02.2020 по 18.05.2020</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td class="time">09:50-11:25</td><td>&nbsp;</td><td class="type-lab">Информационные технологии - лаб. А306 <br>с 11.02.2020 по 19.05.2020</td><td class="type-lab">Вычислительная математика Шергин В.В. лаб. А306 <br>с 12.02.2020 по 20.05.2020</td><td class="type-lk">Экономика и управление производством Абрамова Е.А. лк. А317 <br>с 13.02.2020 по 21.05.2020</td><td class="type-lab">Технологии программирования Константинов Е.С. лаб. А310 <br>с 14.02.2020 по 22.05.2020</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td class="time">11:40-13:15</td><td class="type-lk">Электротехника и электроника Дунаев А.М. лк. Г306 <br>с 10.02.2020 по 18.05.2020</td><td class="type-pz">Элективные курсы по физической культуре и спорту - пр.з. спортзал <br>с 11.02.2020 по 19.05.2020</td><td class="type-lk">Психология и педагогика Клейман М.Б. лк. А206 <br>с 12.02.2020 по 20.05.2020</td><td class="type-pz">Элективные курсы по физической культуре и спорту - пр.з. спортзал <br>с 13.02.2020 по 21.05.2020</td><td class="type-pz">Иностранный язык Врыганова К.А., Ганина В.В. пр.з. А305 <br>с 14.02.2020 по 22.05.2020</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td class="time">13:30-15:05</td><td>&nbsp;</td><td class="type-lk">Информационные технологии Бобков С.П. лк. А206 <br>с 11.02.2020 по 19.05.2020</td><td>&nbsp;</td><td class="type-pz">Философия Клейман М.Б. пр.з. К307 <br>с 13.02.2020 по 21.05.2020</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr></tbody></table>
  
  </div><span style="background-color:#F8FFF0;padding:3px;margin-right:5px;">Лекция</span>
  <span style="background-color:#fff0f8;padding:3px;margin-right:5px;">Практика</span>
  <span style="background-color:#e2fdff;padding:3px;margin-

**Comment by K-Voland** [comment]
"нужно
 <div id="form-ajax-node-content"><div style="overflow-x:auto;width:100%;"><table class="schedule" style="overflow: wrap" autosize="1"><tbody><tr><td rowspan="2" class="week">нед</td><td rowspan="2" class="time">Время</td><td colspan="7" class="zan">Занятия</td></tr><tr><td class="day">Понедельник</td><td class="day">Вторник</td><td class="day">Среда</td><td class="day">Четверг</td><td class="day">Пятница</td><td class="day" style="background-color:#fbdb69">Суббота</td><td class="day">Воскресенье</td></tr><tr><td rowspan="4" style="vertical-align: middle;font-weight: bold;">1</td><td class="time">08:00-09:35</td><td class="type-lk">Технологии программирования Константинов Е.С. лк. А206 <br>с 17.02.2020 по 11.05.2020</td><td>&nbsp;</td><td class="type-lab">Вычислительная математика Шергин В.В. лаб. А204 <br>с 19.02.2020 по 13.05.2020</td><td>&nbsp;</td><td class="type-pz">Экономика и управление производством Абрамова Е.А. пр.з. А205 <br>с 21.02.2020 по 15.05.2020</td><td class="type-lab">Технологии программирования Константинов Е.С. лаб. А306 <br>с 22.02.2020 по 16.05.2020</td><td>&nbsp;</td></tr><tr><td class="time">09:50-11:25</td><td class="type-pz">Психология и педагогика Клейман М.Б. пр.з. А102 <br>с 17.02.2020 по 11.05.2020</td><td>&nbsp;</td><td class="type-lab">Технологии программирования Константинов Е.С. лаб. А309 <br>с 19.02.2020 по 13.05.2020</td><td>&nbsp;</td><td class="type-lk">Философия Клейман М.Б. лк. К205 <br>с 21.02.2020 по 15.05.2020</td><td class="type-lk">Вычислительная математика Шергин В.В. лк. А317 <br>с 22.02.2020 по 16.05.2020</td><td>&nbsp;</td></tr><tr><td class="time">11:40-13:15</td><td class="type-lk">Электротехника и электроника Дунаев А.М. лк. Г306 <br>с 17.02.2020 по 11.05.2020</td><td class="type-pz">Элективные курсы по физической культуре и спорту - пр.з. спортзал <br>с 18.02.2020 по 12.05.2020</td><td>&nbsp;</td><td class="type-pz">Элективные курсы по физической культуре и спорту - пр.з. спортзал <br>с 20.02.2020 по 14.05.2020</td><td class="type-pz">Иностранный язык Врыганова К.А., Ганина В.В. пр.з. А305 <br>с 21.02.2020 по 15.05.2020</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td class="time">13:30-15:05</td><td>&nbsp;</td><td class="type-lk">Информационные технологии Бобков С.П. лк. А206 <br>с 18.02.2020 по 12.05.2020</td><td>&nbsp;</td><td class="type-pz">Философия Клейман М.Б. пр.з. К307 <br>с 20.02.2020 по 14.05.2020</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td rowspan="5" style="background-color:#fbdb69;vertical-align: middle;font-weight: bold;">2</td><td class="time">08:00-09:35</td><td>&nbsp;</td><td>&nbsp;</td><td class="type-lk">Вычислительная математика Шергин В.В. лк. А206 <br>с 12.02.2020 по 20.05.2020</td><td>&nbsp;</td><td class="type-pz">Экономика и управление производством Абрамова Е.А. пр.з. А205 <br>с 14.02.2020 по 22.05.2020</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td class="time">08:00-11:25</td><td class="type-lab">Электротехника и электроника - лаб. Д1.14 <br>с 10.02.2020 по 18.05.2020</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td class="time">09:50-11:25</td><td>&nbsp;</td><td class="type-lab">Информационные технологии - лаб. А306 <br>с 11.02.2020 по 19.05.2020</td><td class="type-lab">Вычислительная математика Шергин В.В. лаб. А306 <br>с 12.02.2020 по 20.05.2020</td><td class="type-lk">Экономика и управление производством Абрамова Е.А. лк. А317 <br>с 13.02.2020 по 21.05.2020</td><td class="type-lab">Технологии программирования Константинов Е.С. лаб. А310 <br>с 14.02.2020 по 22.05.2020</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td class="time">11:40-13:15</td><td class="type-lk">Электротехника и электроника Дунаев А.М. лк. Г306 <br>с 10.02.2020 по 18.05.2020</td><td class="type-pz">Элективные курсы по физической культуре и спорту - пр.з. спортзал <br>с 11.02.2020 по 19.05.2020</td><td class="type-lk">Психология и педагогика Клейман М.Б. лк. А206 <br>с 12.02.2020 по 20.05.2020</td><td class="type-pz">Элективные курсы по физической культуре и спорту - пр.з. спортзал <br>с 13.02.2020 по 21.05.2020</td><td class="type-pz">Иностранный язык Врыганова К.А., Ганина В.В. пр.з. А305 <br>с 14.02.2020 по 22.05.2020</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td class="time">13:30-15:05</td><td>&nbsp;</td><td class="type-lk">Информационные технологии Бобков С.П. лк. А206 <br>с 11.02.2020 по 19.05.2020</td><td>&nbsp;</td><td class="type-pz">Философия Клейман М.Б. пр.з. К307 <br>с 13.02.2020 по 21.05.2020</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr></tbody></table>
  
  </div><span style="background-color:#F8FFF0;padding:3px;margin-right:5px;">Лекция</span>
  <span style="background-color:#fff0f8;padding:3px;margin-right:5px;">Практика</span>
  <span style="background-color:#e2fdff;padding:3px;margin-"
